services:
    ldap_authenticator:
        class: CDesign\LdapBundle\Ldap\LdapAuthenticator
        arguments:
            container:      @service_container
            encoderFactory: @security.encoder_factory

    ldap_userprovider:
        class: CDesign\LdapBundle\Ldap\LdapUserProvider
